ba_2motifs:
  groundtruth: "True"
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 20
  num_epochs: 300
  lr: 0.001
  weight_decay: 0.0000
  dropout: 0.0
  readout: "max"
  batch_size: 200
  unseen: "False"

common_params: &common_params
  graph_classification: "True"
  num_layers: 3
  hidden_dim: 32
  num_epochs: 200
  lr: 0.001
  weight_decay: 0.0005
  dropout: 0.0
  readout: "max"
  batch_size: 64
  gamma: 0.5
  milestones: [70, 90, 120, 170]
  num_early_stop: 50
  unseen: "False"

mutag:
  <<: *common_params
  groundtruth: "True"
  explained_target: 0

benzene:
  <<: *common_params
  groundtruth: "True"
  explained_target: 1

bbbp:
  <<: *common_params
  groundtruth: "False"
  explained_target: 1
